### ISSUE TITLE
Add a search option to load jobs to or from custom marker airports

### ISSUE THREAD

**Issue by Mcewan** [piero-la-lune/FSE-Planner#100]
I use custom markers for a kind of 'bus route' itinerary where pax and cargo are picked up and dropped off along the way.
When flying this route it would be useful to have an option to see only those jobs that are relevant.
This could be implemented as either a search option (alternative to named countries or map area), or as a filter to restrict displayed jobs.

**Comment by piero-la-lune** [comment]
Very similar to #95

**Comment by piero-la-lune** [comment]
Implemented: you can now select a custom layer as the list of airports to use when loading jobs
