### ISSUE TITLE
Requesting Add Plane Boeing 247D W42

### ISSUE THREAD

**Issue by IM0001GT** [piero-la-lune/FSE-Planner#135]
Hello,

It looks like the new fantastic Boeing 247D by Wing42 was added to FSE (In what seems like record time). 
It appears as the "Boeing 247D W42" and is a separate plane from the previously existing in FSE and FSE-Planner "Boeing 247D".

Could this plane please be added?

Thank You

**Comment by piero-la-lune** [comment]
Hello,

Added in the new version just released. Enjoy!
