### ISSUE TITLE
Error processing jobs

### ISSUE THREAD

**Issue by wiseman** [piero-la-lune/FSE-Planner#14]
I'm using https://piero-la-lune.fr/fseplanner/. Currently when I try to download jobs for US-Wisconsin, I get the following error in the console:

```
TypeError: Cannot read property 'lat' of undefined
    at Update.js:133
    at Update.js:273
    at t (Update.js:240)
    at Update.js:258
```

The code pops up a dialog telling me it wasn't able to download the data, but I can see in Chrome's developer tools that the request is succeeding.

Request URL: https://piero-la-lune.fr/fseplanner/proxy/data?userkey=my_user_key&format=csv&query=icao&search=jobsfrom&icaos=5E6-00WI-01WI-02C-02WI-03WI-04WI-05WI-06WI-07WI-08WI-09WI-0WI1-0WI2-0WI4-0WI5-0WI6-0WI7-0WI8-0WI9-0WN5-10WI-11WN-13WI-14WI-14WS-15WI-16WI-17WI-19WI-1WI0-1WI1-1WI2-1WI3-1WI5-1WI6-1WI7-1WI8-1WI9-1WN1-1WN2-1WN3-20WI-21WI-24WI-26WI-27WI-28WI-29WI-2P2-2T5-2WI0-2WI1-2WI2-2WI4-2WI5-2WI6-2WI7-2WI8-2WI9-2WN2-2WN3-2WN4-2WN5-2WN6-2WN7-2WN8-30W-30WI-31WI-31WN-32WI-34WI-35WI-36WI-37WI-38WI-39WI-3CU-3D1-3D2-3T3-3WI0-3WI1-3WI2-3WI3-3WI4-3WI5-3WI6-3WI7-3WI8-3WI9-3WO-40D-40WI-41WI-43WI-44C-44WI-45WI-47WI-48WI-49C-49WI-4D1-4P5-4R5-4WI0-4WI1-4WI2-4WI3-4WI4-4WI5-4WI6-4WI7-4WI8-4WI9-4WN4-50WI-51WI-52WI-53WI-54WI-55C-55WI-56WI-57C-57WI-58C-58WI-59WI-5G4-5K6-5N2-5WI0-5WI1-5WI2-5WI3-5WI4-5WI5-5WI6-5WI8-5WI9-5Y3-60C-61C-61WI-62C-63C-63WI-64C-64WI-65WI-65WN-66WI-67WI-68C-6M5-6P3-6WI0-6WI1-6WI2-6WI3-6WI4-6WI5-6WI6-6WI7-6WI9-70WI-72WI-73C-73WI-75WI-76C-77WI-78WI-79C-79WI-7P5-7V3-7WI0-7WI1-7WI2-7WI4-7WI5-7WI6-7WI7-7WI8-7WI9-80WI-81WI-82C-82WI-83WI-84C-86WI-87WI-87Y-88C-88WI-89WI-8D1-8W1-8WI0-8WI1-8WI2-8WI3-8WI5-8WI6-8WI7-8WI8-90WI-91C-91WI-92C-92WI-93C-93WI-94C-95WI-96C-96WI-97WI-99C-99WI-9WI1-9WI2-9WI3-9WI4-9WI5-9WI6-9WI7-9WI8-9WI9-9WN1-9WN2-9WN3-9WN4-9WN5-9WN6-9WN8-9WN9-9Y7-C02-C29-C35-C37-C47-C59-C74-C89-D25-HBW-JB01-KAHH-KAIG-KARV-KASX-KATW-KAUW-KBCK-KBDJ-KBUU-KCLI-KCMY-KCWA-KDAF-KDLL-KEAU-KEFT-KEGV-KENW-KETB-KFLD-KGRB-KGTG-KHXF-KHYR-KISW-KJVL-KLNL-KLNR-KLSE-KMDZ-KMFI-KMKE-KMRJ-KMSN-KMTW-KMWC-KOCQ-KOEO-KOLG-KOSH-KOVS-KPBH-KPCZ-KPDC-KPKF-KPVB-KRAC-KRCX-KRHI-KRNH-KRPD-KRRL-KRYV-KRZN-KSBM-KSSQ-KSTE-KSUE-KSUW-KUBE-KUES-KUNU-KVIQ-KVOK-T08-W11-W19-W23-W26-W34-WI00-WI02-WI03-WI04-WI05-WI07-WI09-WI10-WI11-WI12-WI13-WI14-WI16-WI18-WI19-WI20-WI21-WI22-WI23-WI24-WI25-WI26-WI27-WI28-WI29-WI31-WI32-WI33-WI35-WI36-WI37-WI40-WI42-WI43-WI46-WI47-WI48-WI49-WI50-WI51-WI52-WI53-WI54-WI55-WI56-WI58-WI60-WI61-WI62-WI65-WI66-WI67-WI69-WI70-WI71-WI72-WI73-WI74-WI75-WI76-WI77-WI78-WI79-WI81-WI84-WI86-WI87-WI88-WI89-WI90-WI91-WI92-WI95-WI97-WI98-WI99-WN03-WN11-WN27-WN28-WN39-WN44-WN46-WN63-WN66-WN75-WN86-WN90-WS01-WS02-WS04-WS05-WS06-WS08-WS09-WS10-WS11-WS12-WS13-WS14-WS15-WS16-WS17-WS19-WS20-WS22-WS23-WS24-WS25-WS26-WS28-WS29-WS30-WS31-WS32-WS33-WS36-WS39-WS41-WS42-WS43-WS44-WS45-WS46-WS49-WS51-WS55-WS60-WS62-WS64-WS67-WS68-WS69-WS71-WS72-WS74-WS76-WS81-WS96-Y23-Y50-Y51-Y55-Y72-Y77

I've put the CSV content in the response in this gist: https://gist.github.com/wiseman/25e173ef00a685e4979f32802452940d

**Comment by wiseman** [comment]
By the way, I just wanted to mention that this is the most modern, nicest looking, easiest-to-use planner I've found.  Good job!

**Comment by icykoneko** [comment]
I have a fix for this :)  MN24 seems to be the culprit in my testing, but there might be others.

**Comment by piero-la-lune** [comment]
I just did a quick check, it seems that MN24 is not included in the `icaodata-with-zones.json` file. I have no idea why, because the airport list it supposed to come directly from FSE. I must have done something wrong at some point, when generating this file.

Anyway, I have to regenerate the file, and ensure no other airport is missing. It will fix the issue.

@icykoneko: in the meantime, your MR does seem to fix the issue, thanks!

**Comment by piero-la-lune** [comment]
The investigation continues...

* MN24 is the only airport missing
* I now remember why: 8Y4 has the exact same coordinates in FSE, which make MN24 unusable (it is impossible to land at MN24) => That is why I had completely removed it, but this was obviously a mistake...

**Comment by piero-la-lune** [comment]
Pull request #24 should fix the bug.
