### ISSUE TITLE
Update for FSE's latest "My Flight" page and "Max Cargo Weight" Changes.

### ISSUE THREAD

**Issue by IM0001GT** [piero-la-lune/FSE-Planner#140]
As the title states, looks like the URL for the My Flight page changed to remove the "v2" so when you have the Planner Rent the plane or add all the jobs in a plan, when it open the My Fight page it goes to a broken link now. The Plane and Jobs are added correctly still however. 

Also I assume the changes for the Max Cargo Weight for the list of planes is going to make finding routes a whole bunch of fun now.

Copied from the announcement page. "https://www.fseconomy.net/welcome"

Below is a list of aircraft that will be changed immediately. 
Any of these aircraft that are currently airborne during the code update 
will not be impacted for that flight. However, the next attempted 
takeoff will be subject to the new maximum cargo restrictions.

AIRCRAFT | New Value | Old Value | Difference
-- | -- | -- | --
Aero Vodochody L-39 | 200 | 4253 | -4053
Aircreation 582SL | 100 | 278 | -178
BAC Jet Provost T5 | 200 | 1951 | -1751
Boeing Stearman | 200 | 354 | -154
Bombardier Challenger 300 | 500 | 6849 | -6349
Bombardier Challenger 650 | 500 | 8548 | -8048
Bombardier Lear 60 | 500 | 4019 | -3519
Cessna Citation CJ1 | 400 | 1878 | -1478
Cessna Citation CJ4 (MSFS) | 500 | 3098 | -2598
Cessna Citation II | 500 | 3357 | -2857
Cessna Citation Longitude | 500 | 7011 | -6511
Cessna Citation X | 500 | 6714 | -6214
Cessna Citation XLS+ | 500 | 3674 | -3174
Cessna Mustang | 400 | 1390 | -990
Cirrus Vision SF50 | 400 | 1102 | -702
Curtiss P-40C (A2A) | 200 | 968 | -768
Dassault Falcon 50 | 500 | 8437 | -7937
Dassault Falcon 7X | 500 | 16279 | -15779
DeHavilland DH80A Puss Moth | 200 | 355 | -155
Eclipse 500 | 400 | 1162 | -762
Embraer Legacy 600 | 500 | 8500 | -8000
Embraer Phenom 100 | 400 | 1515 | -1115
Embraer Phenom 300 | 500 | 3219 | -2719
Fairchild PT19/26 Cornell | 200 | 351 | -151
Hawker 850XP | 400 | 5362 | -4962
Honda HA-420 HondaJet | 400 | 1541 | -1141
Lear 45 | 500 | 3958 | -3458
Learjet 24B | 400 | 2920 | -2520
Learjet 24B - Tip Tanks | 400 | 2799 | -2399
Learjet 35A | 400 | 4012 | -3612
LearJet LJ25D | 500 | 3338 | -2838
Lockheed P-38 Lightning | 200 | 2159 | -1959
Morane-Saulnier MS-760 | 200 | 1525 | -1325
New Standard D25A | 200 | 585 | -385
North American P-51D Mustang | 200 | 2363 | -2163
North American T-28 Trojan | 200 | 942 | -742
North American T-39 Sabreliner | 400 | 3758 | -3358
North American T-6G Texan | 200 | 1188 | -988
Raytheon Beechjet / Hawker | 500 | 2767 | -2267
Raytheon Premier1 | 400 | 2081 | -1681
Stinson 108 | 200 | 489 | -289
Supermarine Spitfire | 200 | 988 | -788
Waco Classic YMF | 200 | 338 | -138

**Comment by piero-la-lune** [comment]
Thanks, I am aware of many breaking changes and am working on a fix

**Comment by piero-la-lune** [comment]
Fixed and released

**Comment by IM0001GT** [comment]
Yea only made the post juuuust because I wasn't sure if you were made aware. (Obviously you're on top of it.)

Damn you work fast. Great stuff!

**Comment by piero-la-lune** [comment]
Thanks :)
