### ISSUE TITLE
Wording for passengers weight in route finder is confusing

### ISSUE THREAD

**Issue by notPronoe** [piero-la-lune/FSE-Planner#145]
When showing a route information, if there are only passenger scheduled for a given leg, the total will say "Total: 2 passengers and 154kg". 

Instead it should read something like "Total: 2 passengers (154kg) and 0 cargo (0 kg)". Or something similar.

**Comment by piero-la-lune** [comment]
This is intended: the total should sum up both the passengers weight and the cargo weight (if any). I will remove the "and" that can make it confusing, to "Total: 2 passengers • 154kg"
