### ISSUE TITLE
Add a "Add to my flight" link to the generated PDF

### ISSUE THREAD

**Issue by notPronoe** [piero-la-lune/FSE-Planner#147]
Sometimes my PC will crash and the only traces I have left of flights I had scheduled are the PDF I exported. It would be nice if there was a link in this PDF to add flights to "My Flight". 

Particularly useful if a leg includes VIP or if multiple plans were exported.

**Comment by piero-la-lune** [comment]
Unfortunately, this is not technically feasible with a PDF file.
