### ISSUE TITLE
Could not get data: Error: Invalid ICAO list message when loading jobs data

### ISSUE THREAD

**Issue by mikehilbert** [piero-la-lune/FSE-Planner#149]
This just started to happen today, everything worked fine yesterday.
[debug (2).json.txt](https://github.com/piero-la-lune/FSE-Planner/files/9944061/debug.2.json.txt)

**Comment by piero-la-lune** [comment]
After a first quick investigation, there is an issue with the Custom Area selected (out of bounds). I have to continue investigating to understand how it happened. In the meantime, unselect then select again "Custom Area" and draw again your desired area.

**Comment by piero-la-lune** [comment]
Found the bug: when changing the map center in the settings, the Custom Area can break. I fixed the bug, but the fix will not be released immediately.

In the meantime, this is the way to prevent it from happening: if you get the error (or if you do not see the blue box in the Custom Area popup), change back the "map center" parameter to its previous value in Settings. This will allow you to see again the blue box and move it around.

With the file you gave me, I can tell you that you need to set the map center to -180 to make it work. If you need to set it back to +180, first drag the blue box to the right most end of the map, and only then switch back to +180.

**Comment by mikehilbert** [comment]
Thank you. I did have a problem of not finding the box depending on where
the map was centered.

Mike
