### ISSUE TITLE
Reset filters

### ISSUE THREAD

**Issue by sanhozay** [piero-la-lune/FSE-Planner#152]
When I am looking for jobs, I often use filters. If I don't find anything suitable, I might load data from a different area and the filters will still be active. Sometimes I might want them but often I will not.

Could I suggest adding a reset/clear button to the filter bar?

Another possibility would be an addition to the filters settings to clear filters when loading new jobs?

**Comment by piero-la-lune** [comment]
Good idea
I am working on it
