### ISSUE TITLE
Add HexColorInput to input icon color

### ISSUE THREAD

**Issue by ariefwt** [piero-la-lune/FSE-Planner#157]
Hello again,

I have a minor enhancement request: can we add a `HexColorInput` to the icon color picker, so that we can copy and paste color hex code?

Something like this: https://codesandbox.io/s/0k2fx?file=/src/App.js

Over here (and other similar places):
![image](https://user-images.githubusercontent.com/7259322/224519913-b1aa1bce-d9cb-440f-a2ef-cc580982ee71.png)

Thank you!

**Comment by piero-la-lune** [comment]
Will look into it when I have the time

**Comment by piero-la-lune** [comment]
Implemented, will be available with the next FSE Planner release
