### ISSUE TITLE
FSE airports with alternative shown as unavailable

### ISSUE THREAD

**Issue by ariefwt** [piero-la-lune/FSE-Planner#159]
Hello,

I'd like to show you something, which may or may not be a bug

I set the Simulator setting to MSFS, like this:
![image](https://github.com/piero-la-lune/FSE-Planner/assets/7259322/dc589296-a4f7-41fb-9211-1e2d71b5acd6)

And I recently noticed that there are some FSEconomy airports which appear to have at least one MSFS alternative airport around them (visually appears close by and within the FSE airport landing area grid lines) but are marked as unavailable (with double strikethrough) and thus are excluded from the route finder

I have two examples: FSEconomy's `SWGR` and `SB4D`

![image](https://github.com/piero-la-lune/FSE-Planner/assets/7259322/62c08525-ef80-4741-93e8-b42481b0c45e)

![image](https://github.com/piero-la-lune/FSE-Planner/assets/7259322/5515c239-db24-4021-af05-aae799f538ef)

In both cases, there is at least one MSFS alternative within the FSE airport landing area, but `SWGR` is marked as unavailable, while `SB4D` is "renamed" to `SSZJ`

I expected both airports to be marked as available, `SWGR` could've been "renamed" to `SWDC` and be part of the route finder

Here's my `debug.json` if necessary:
[debug.json.txt](https://github.com/piero-la-lune/FSE-Planner/files/11458513/debug.json.txt)

**Comment by piero-la-lune** [comment]
This is the intended behavior.

If you zoom in around the SWGR area, you will see that the FSE and MSFS airports are not exactly at the same spot, FSE Planner considers those two locations as **different airports**.
However, you can clearly see that the SB4D (FSE) and SSZJ (MSFS) ICAOs reference the **same airstrip**.

If the distance is greater than 2km (arbitrary distance I chose), FSE Planner will consider that the MSFS airport is a valid landing area for the given FSE airport, but will consider that this is however **a different airport** (and therefore make the FSE location appear as closed).

On the contrary, if the distance is less than 2km, FSE Planner will consider that the airport still exists, but has changed its ICAO.

**Comment by ariefwt** [comment]
Hmmm but this arbitrary 2 km distance unfortunately means airports we can use is hidden from route finder, despite having lots of assignments.

Is it possible to have an alternative mechanism, where as long as there's a simulator-compatible airport within the FSEconomy landing area, it'll be made available in route finder? This way, we can fly to more places we previously thought we can't.

**Comment by piero-la-lune** [comment]
I have added a new parameter to allow for this:

![image](https://github.com/piero-la-lune/FSE-Planner/assets/614507/ec3b8447-5385-4c3e-90eb-3ff1e3b1a2e4)

It will be shipped with the next FSE Planner release
