### ISSUE TITLE
Route planner not running

### ISSUE THREAD

**Issue by wiseman** [piero-la-lune/FSE-Planner#16]
When I clone this, run `npm install` and `npm start`, and open the app at localhost, everything seems to work except for route planning. When I try to start the route planner, the progress bar never changes, and no results are ever processed.

Is there a trick to getting it to run locally?

**Comment by piero-la-lune** [comment]
It should work, what browser are you using? Could you open your browser Developer Tools (usually `Ctrl` + `Maj` + `I`), and see if there is any error in the console?

**Comment by wiseman** [comment]
I don't know what was happening before, but it seems to be working fine now. If I run into any issues I'll re-open. Thank you!
