### ISSUE TITLE
Possible to add origin and destination constraints on route planner?

### ISSUE THREAD

**Issue by wiseman** [piero-la-lune/FSE-Planner#17]
Say I want to start at CYYZ and end at CYZV. Is there currently a way to add those constraints to the route planner?

(Ideally I'm imagining it would trade off distance for dollars, e.g. something like 1 nm additional distance is counted as a $5 penalty, with that 1:5 ratio being configurable.)

**Comment by piero-la-lune** [comment]
Yes, there is a way. In Route Planner, click on 'Free search' then enter the origin and destination airport:
![image](https://user-images.githubusercontent.com/614507/103513628-3f930900-4e6b-11eb-827a-0b44955517ea.png)

**Comment by wiseman** [comment]
Great, that's exactly what I wanted. Thank you.
