### ISSUE TITLE
Paste list of ICAO(s) in Route Finder Filter

### ISSUE THREAD

**Issue by TomScogg** [piero-la-lune/FSE-Planner#176]
Hi,

is is possible to paste a list of ICAO(s) separated by a comma in the Route Finder Filter?

Also, to have this feature in the Route Finder Settings to be able to save a List of ICAO(s) as a Default option?

Thank You

**Comment by piero-la-lune** [comment]
Hi, what is the use case exactly? I am not sure why you would want to have multiple ICAOs in the filter

**Comment by TomScogg** [comment]
Hi, Thanks for looking at this. At the moment I can only use a single ICAO. I have a list of ICAOs and I wanted to be able to add them all in one go as a filter and use those to only show the available routes that might exist (directly / indirectly) between them on the Map.

Cheers!

**Comment by piero-la-lune** [comment]
I have implemented a fix that should allow you to paste multiple ICAOs at once. However, I will not have filters saved as default options, this is not the intended usage for filters.
Should be released soon in the next version
