### ISSUE TITLE
Unbuilt lots overlay should not include FBOs in Lottery

### ISSUE THREAD

**Issue by piero-la-lune** [piero-la-lune/FSE-Planner#29]
okgood:

> I noticed it shows FBOs currently in the FBO lottery as “unbuilt”. While technically I suppose this is true because the FBO is closed, it’s not really available to be built on because it’s in the lottery (and in the examples I found, already had a ticket purchased so it also won’t be available going forward). Just wanted to bring this to your attention. Ideally, in my opinion, “unbuilt FBOs” should only show airports where a user can build an FBO.

**Comment by piero-la-lune** [comment]
The unbuilt overlay does show lots currently in the lottery.

It is not by choice, but by necessity, the only way I found to get the unbuilt list automatically includes them.

And there is no easy way to programmatically remove them, so it probably will stay that way, unless there are some changes on FSE side

**Comment by jsjunior** [comment]
The endpoint `https://server.fseconomy.net/rest/api2/map/fbos/lottery` list FBOs currently in the lotery. Could it be a solution?

**Comment by piero-la-lune** [comment]
Fixed, thanks jsjunior
