### ISSUE TITLE
Route Finder doesn't fill plane with jobs along the way to destination

### ISSUE THREAD

**Issue by icykoneko** [piero-la-lune/FSE-Planner#33]
I've noticed that the Route Finder does good for dropping off pax at multiple spots, but it completely ignores filling the plane enroute to a destination.

For example, say you have departure airport that's 50 NM from destination, bearing 180 deg, but only 5 pax.  You can hold 5 more (based on the inputs).  Let's suppose there's an airport 40 NM, bearing 170 deg from the destination with 3 more pax.  I would expect the Route Finder to pick up those pax as well, but in practice, it will only choose one of the other, both of which are kinda meh :(

**Comment by piero-la-lune** [comment]
You are absolutely right, the algorithm considers on-route stops for dropping off pax, but not loading them. Not so easy to implement without breaking everything, but should be doable, I will look into it. Thanks!
