### ISSUE TITLE
Suggestion: Route must start from specific ICAO / filter routes by ICAO

### ISSUE THREAD

**Issue by IKatsu** [piero-la-lune/FSE-Planner#34]
Not sure how feasible this would be but an option to have a specific ICAO as a starting location would be nice.
This from the point of where you have your own or group plane somewhere.

That said, maybe also an option to only use group planes ?

**Comment by piero-la-lune** [comment]
I assume you are talking about the Route Finder?

I think this is already possible: in the Route Finder, select "Free Search" and enter a starting ICAO (you do not need to enter a destination).

![image](https://user-images.githubusercontent.com/614507/107826642-8129a480-6d85-11eb-85b6-6f3fee12dd6e.png)

**Comment by piero-la-lune** [comment]
(I will keep in mind your suggestion for showing and using group planes, instead of rentable planes, for the next release)

**Comment by piero-la-lune** [comment]
I have added the option to load user and group planes (instead of publicly available planes).

Not sure if my previous answer helped you, or if you still think the app can be further improved?

**Comment by IKatsu** [comment]
Should be good.
I've been too busy to fly around but if I have any further ideas I'll post em up ;)

**Comment by piero-la-lune** [comment]
Great, do feel free to share your ideas :)
