### ISSUE TITLE
Could you please add the Cessna Longitude?

### ISSUE THREAD

**Issue by jonasbeaver** [piero-la-lune/FSE-Planner#36]
the cessna citation longitude now included in FSE, you can see it in the aircraft models here:

https://server.fseconomy.net/aircraftconfigs.jsp

👍

**Comment by piero-la-lune** [comment]
Sure, I will add it ASAP

**Comment by piero-la-lune** [comment]
The aircraft models were updated. It's live on https://piero-la-lune.fr/fseplanner/
