### ISSUE TITLE
can we open a wish list thread? :)

### ISSUE THREAD

**Issue by jonasbeaver** [piero-la-lune/FSE-Planner#39]

**Comment by jonasbeaver** [comment]
(Salvaged from a closed issue thread I posted to as it closed)

but... if I do have this thread as a bit of a wish list:

In the filters is min/max duration for total flight time for the whole route or per leg, and would it be possible to have a total flight time min/max for the whole trip and a max leg distance filter for the whole trip?

I've been making a ton of money with the CJ4 and Citation Longitude in MSFS, mostly because of this tool you have created!

I will usually select a number of middle eastern countries, eastern and northern europe, and russia as my regions to job search, select the CJ4 as the rentable airplane, and see what comes up. The reason I ask is if I filter by best pay per flight time or per mile almost always ends up with a 48nm trip for ~$4k which is not what I'm trying to do. Doing this search, I usually get routes with a total pay ~50-70k varying between 7-12 hours flight time with the CJ4 parameters set to 10 passengers and 1500kg. So far, I have been filtering by total pay and checking total flight times. In the example today, the suggested routes are between 10.5 and 14 hours (~3000nm). If I could filter so the total leg distance didn't exceed the range of the plane (which I believe I can set now in the filter) AND the total overall flight distance could be limited to my choice (say 12 hours, or no more than 3000nm for the entire trip) I could fine tune my selections better. What I am currently doing is sorting by Total Pay, and finding the shortest timed trip within a few thousand dollars of best pay. The best trip today for total pay is $77205 and 12h11. There is another trip at $73647 but its only 10h58. If I could filter for best pay per mile but only on trips over 10 hours for the total flight for example I think I could better choose the route to fly. I could also find the best 5 hour routes that way.

Another thing I'm up to is, I'm trying to get a DA62 from europe to north america, and this route planner has been excellent for that. It would be useful to have in the free search not just the airport you are starting and ending from, but if it was possible to force an intermediate stop. I wanted very much to go through Vagar in the Faroe Islands on my way to Iceland (I've made it to Keflavik already and because of your planner I did it +$24k instead of paying to ferry or trying to find my own routes). There were trips to and from it along the route, but I couldn't get the route finder to include it. That said, the flight planner is EXCELLENT for manually choosing your legs as well, it just takes some observation and clicking.

One other area I still find myself looking for alternative resources away from your flight planner is finding alternative airports when FSE and MSFS databases are not the same. Currently I am using this: https://fse-aardvark-planner.co.uk/msfs-icaos/ to find the best alternative airport when it doesn't exist in MSFS. Your planner will let me know an FSE airport doesn't exist, and lists multiple alternatives, but the link I sent you shows a green box of the region in which to land for it to count as the FSE listed airport AND all the airports (if there are any) which would be acceptable as alternative landing airports. Your planner is already good in this respect, but it could be a little better. This is a fairly rare circumstance, but flying in the middle east and russia (that's where the big bucks are in FSE) its a bit more common.

Please note, these are not bugs or complaints, I am using your tool almost every day now (if you see a lot of hits on your site from Texas thats me!). It is very quickly coming to the point where I don't do a flight without using your planner first.

Thank you!

btw If you had a flight sim that has a citation mustang in it, and you'd like one for FSE, I bought one by accident and would be happy to sell it to you for what I paid for it :)

**Comment by piero-la-lune** [comment]
1. The min/max distance/$/duration filters are for the whole trip: i will think about adding the same kind of filters for a single leg
2. Intermediate stop: I have to think more about it, not sure how complex it would be to implement
3. You can already show the FSE airport landing areas: in the overlay list, select "FSE airport landing areas" + "MSFS airports" so you can visualize which airports are in the zone

And thanks for the offer on the citation mustang, but I am using MSFS...

**Comment by jonasbeaver** [comment]
Every time I've had a question or an issue, you've been able to show me in 2 seconds that your tool can already do that!

I hope I'm not getting annoying yet :)

Thanks again for this great tool

**Comment by piero-la-lune** [comment]
Ahah no worries :) I do know it is not always easy to find a feature, the tool is more and more complex

**Comment by jonasbeaver** [comment]
By the time I understand all the useful features I haven't even touched yet, I'll be able to write the manual for you :)

**Comment by jonasbeaver** [comment]
I was going to ask if there was a way to turn on and off the distance bonus accounting as it is currently suspended in FSE and not calculated.

I was also going to see if you could account for booking fees in the calculations when taking 6 or more green contracts, or if this is already done.
And if you wanted to go all out, you could take into account the ground handling fees at different airports 🥇 or if that was done as well.

**Comment by piero-la-lune** [comment]
Distance bonus is on again :)

The pay that is displayed is the gross pay, it does not take into account booking or ground fees. For rental, it takes into account the distance bonus, but not fuel or rental costs. I do intend to later add the net pay (taking into account all those additional fees): it's in the TODO.

**Comment by piero-la-lune** [comment]
New release:
- bookings fees, ground handling fees, plane rental, bonus and fuel cost can now be taken into account.
- legs now cannot exceed the plane maximum range

I believe there only remains one of your suggestion that I have not implemented yet: intermediate stops

**Comment by piero-la-lune** [comment]
Thanks to icykoneko, the new release now offer you the possibility to filter the Route Finder results, to only keep the route containing a given ICAO.

I am closing this thread, because I believe all your suggestions have been implemented, but fill free to open a new one if needed!
