### ISSUE TITLE
Add option to include "My Flight" jobs in route finder calculations

### ISSUE THREAD

**Issue by icykoneko** [piero-la-lune/FSE-Planner#44]
Sometimes you've already reserved a few jobs, but still want to compute routes. I can see where you wouldn't want this to be the default, so it'd be nice if we had the option to include those jobs too.

**Comment by piero-la-lune** [comment]
Not sure how this would work. Should the route starts with these jobs (in which order?)? Should the route contain these jobs, but can start anywhere and end anywhere?

**Comment by icykoneko** [comment]
I was thinking just have the jobs be part of the available jobs again. Just
so you can reserve them but midway through you decide, hey are there better
routes I could take at this point.

On course it’s up to the user to update their jobs, and airplanes first.

**Comment by piero-la-lune** [comment]
Added to v1.5.0 now live
