### ISSUE TITLE
Keeps crashing

### ISSUE THREAD

**Issue by Thingyman-DEV** [piero-la-lune/FSE-Planner#46]
Whenever I use route finder, it crashes right at the very end and gives this code:
SBOX_FATAL_MEMORY_EXCEEDED
I have a decent system, 16 gigs of ram and a 5600X, and checked task manager and was only getting about 4-5 gigs of memory usage and 60% cpu.
I've closed all other programs.
Is there something I'm doing wrong?

**Comment by piero-la-lune** [comment]
That is weird, I have never seen this. Some questions to help troubleshoot:
* What browser (Chrome, Firefox, etc.) are you using? Could you try with another one and see if you have the same issue?
* What job area have you loaded?
* Could you share the parameters you are setting for your route searches?
