### ISSUE TITLE
VIP Only search is including cargo that won't fit

### ISSUE THREAD

**Issue by IKatsu** [piero-la-lune/FSE-Planner#47]
For some reason the VIP only search is including cargo jobs that do not fit. 
I've not noticed this before so not sure if it's a glitch in FSE itself or FSE planner.
I normally fly in Europe where large cargo jobs aren't that common but for this one I had loaded up the whole of the US

Ex:
7712kg VIP to KFAR ($23807)
Total: 7712kg

I only have the c4j loaded which can carry 2500kg.

**Comment by piero-la-lune** [comment]
That is strange and obviously should not happen. I have never seen this, and have not been able to reproduce the issue (the assignment you are mentioning is still there, but it is not showing for me in the Route Finder when using CJ4...). Have you changed any of the default Route Finder settings? Could you share a screenshot of the result list, and a screenshot of the exact route?

**Comment by IKatsu** [comment]
https://i.imgur.com/O8BXM64.png

It does it for the normal non vip only search too I just noticed.
The plane listed there is a citation 2.
I have not changed any of the default settings other than limit to msfs airports.

**Comment by piero-la-lune** [comment]
No luck on my side reproducing the bug :(

I have just released a new version of FSE Planner, with a tool that should help me reproduce the issue next time. Could you please, if you see again the bug, follow these steps :

1. Click on FSE Planner version number, on the top left of the screen
2. Click on "Debug": it should offer you a file called debug.json to download
3. Download the file and share it with me

Hopefully it will have all the necessary info I need to reproduce your bug

**Comment by piero-la-lune** [comment]
I was able to finally reproduce and fix the bug, no need to follow the above procedure. The bug fix will be integrated to the next FSE Planner release, which should be available soon.

Thanks for reporting the issue.
