### ISSUE TITLE
Read Key Error

### ISSUE THREAD

**Issue by dmeador** [piero-la-lune/FSE-Planner#48]
Hi I'm getting error: "Could not get data. Check your read access key and ensure you have not reached your quota limit.  I have verified another application that accesses the FSE data using my same read key just fine.  So the read key I am using is correct.  Could you give me some tips to check?  I am using a local installation of the FSE-Planner.

**Comment by dmeador** [comment]
Pulling up the browser debug window, I noticed the proxy error, and also saw the proxy issue reported.  Pulled the latest source and setup npm+dev.  The latest code is working for me.  I'll close the issue out on myself.

**Comment by piero-la-lune** [comment]
Glad you were able to resolve the issue by yourself. FSE have recently solved the issue on their side, and the proxy in no longer needed. The previous downloadable version still includes it, but it was removed from the master branch, and the change should be included in the next release. You then should not need to use npm at all (as long as you are not using the Route Finder)
