### ISSUE TITLE
Highlight inbound and outbond jobs on airport mouse hover

### ISSUE THREAD

**Issue by piero-la-lune** [piero-la-lune/FSE-Planner#53]
From CptVail:

> Would it be possible to highlight all inbound and outbound assignments, when hovering over an airport? Maybe even in different colours?

**Comment by piero-la-lune** [comment]
It is really complex to implement :( Not the priority right now

**Comment by oobayly** [comment]
Would you be happy with this solution?

**Comment by piero-la-lune** [comment]
Thanks for your contribution, merged into master after a small improvement.

**Comment by oobayly** [comment]
Cool. I hadn't noticed a big hit on performance, probably because I had only selected a small number of jobs.

I hadn't considered the effect of filtering the list of jobs for every marker especially as the vast majority of markers wouldn't have any jobs.
