### ISSUE TITLE
after loading my company's airplanes, received error message and now page only reloads white

### ISSUE THREAD

**Issue by jonasbeaver** [piero-la-lune/FSE-Planner#64]
using the version hosted on your website
hitting refresh still results in a blank page in chrome
is there somewhere to delete some kind of local storage or cache?
still works with the local version and on ms edge

**Comment by piero-la-lune** [comment]
Open FSE Planner, then open de Developer Tools (`F12`):
1. Browse to the `Storage` (Firefox) or `Application` tab
2. Under `Local Storage` on the left, right click `https://piero-la-lune.fr` to clear the local storage

Firefox:
![image](https://user-images.githubusercontent.com/614507/118248838-09af0280-b4a5-11eb-9022-03d8c486c69b.png)


Chrome:
![image](https://user-images.githubusercontent.com/614507/118248757-f7cd5f80-b4a4-11eb-86b1-d1b3d7cdac1b.png)


If the issue persist, could you please:
1. Click on FSE Planner version number, on the top left of the screen
2. Click on "Debug": it should offer you a file called `debug.json` to download
3. Download the file and share it with me

![](https://snipboard.io/DdNxHe.jpg)

Hopefully it should give me all the necessary info I need to reproduce your bug and then fix it.

**Comment by jonasbeaver** [comment]
Thanks!
If it happens again I'll send a report
________________________________

**Comment by icykoneko** [comment]
I ran into this as well recently.  I believe it was complaining about an icao object missing.  If I see it happen again, I'll post debug for ya as well.

**Comment by piero-la-lune** [comment]
Thanks to another user bug report, I have been able to reproduce and fix the bug (it was caused by "in flight" planes when loading planes from FSE).

I have also improved the user experience, in case something similar happens again: an error message will explain what to do, instead of a simple white screen.
