### ISSUE TITLE
Only last entry from "Owned & Leased planes" is searched

### ISSUE THREAD

**Issue by gamewin1** [piero-la-lune/FSE-Planner#69]
Happens on the public instance and from a local installation.

WIth "Rentable Planes" left blank and "Owned & Leased planes" having multiple entries, it seems only the last entry's planes are displayed on the map after updating. Even removing one entry and readding it to the end will cause the previous planes to be removed and the new last entry's planes to appear instead.

**Comment by piero-la-lune** [comment]
It seems there is indeed a bug, thanks for reporting the issue, I will work on it ASAP

**Comment by piero-la-lune** [comment]
Bug is fixed, should be live on piero-la-lune.fr before tomorrow

**Comment by piero-la-lune** [comment]
The bug fix is live piero-la-lune.fr
