### ISSUE TITLE
Not really an issue, just a thank you! (with an idea?)

### ISSUE THREAD

**Issue by jonasbeaver** [piero-la-lune/FSE-Planner#75]
First, thank you! I use this as my primary idea planner now in FSE and have used it very successfully on a tour of South America.

Second, I was curious if after learning how to feed a spreadsheet with data from FSE, would there be a way to use your tools to map what you've flown and somehow use past data in interesting ways?

**Comment by piero-la-lune** [comment]
Thanks for your message :)

As to your question, are your thinking about something in particular? With the "Custom markers" feature, it is possible to highlight certain airports (or even draw a route on the map): you could use this feature to display all the airports you have been to recently, or even display a recent route you have followed.
