### ISSUE TITLE
Maptiles Invalid Key

### ISSUE THREAD

**Issue by jfbuendia** [piero-la-lune/FSE-Planner#97]
Today:
![image](https://user-images.githubusercontent.com/7544232/148643472-24c1303a-4a2c-4e42-89c1-fc406052ec41.png)

Thanks in advance for support and for this awesome tool!

**Comment by jfbuendia** [comment]
Here are the debug file: https://drive.google.com/open?id=1_mXwV8al4XZMkk_Jd0TgBwpZmn77BanO&authuser=jfbuendia%40gmail.com&usp=drive_fs

**Comment by piero-la-lune** [comment]
Thanks for the bug report. It is a know issue. For the secondary base map, I am using a paid service that provides a free tier, but there are too many users that use it and we reach the limit every month: it will work again in a few days. In the meantime, you have to use the default base map.

Unfortunately, there is not many providers that offer map tiles for free, and it quickly become very expensive with paid service :( I am looking into an alternative (generate and host my own map tiles), but it is a rather complex thing to set up.

**Comment by piero-la-lune** [comment]
Fixed in #104, available in next release.
