### ISSUE TITLE
Available aircraft not showing in custom marker airport

### ISSUE THREAD

**Issue by Mcewan** [piero-la-lune/FSE-Planner#98]
First of all, many thanks for this most excellent planner. I find it indispensable.
It seems that when searching for available aircraft, a candidate aircraft at an airport which is a custom marker is not picked up: the airport marker remains just the custom marker colour, and the aircraft is not included in the airport click popup.
I am seeing this at present for the Ju-52 at EGPU.
[debug.zip](https://github.com/piero-la-lune/FSE-Planner/files/7838179/debug.zip)

**Comment by piero-la-lune** [comment]
Thanks for the report. The fact that the custom marker does not change color is intended, but I could at least display the airplanes in the popup if there are any.

**Comment by piero-la-lune** [comment]
Implemented: markers now change color on all layers, and the list of planes is correctly shown in the popup
